print("Hello World")
print("You must be the legendary god that comes from sky")
print("We have been waiting for you for a long time.")
print("Our legend said you will be very tasty with mustard")
print("We will have a feast tonight unless you say")